language: generic

jobs:
    include:
        #
        #
        ### test ###
        - stage: test
          name: bare metal
          before_install:
            - nvm install 12
            - nvm use 12
            - pyenv install -s 3.6.3
            - pyenv global 3.6.3
            - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
            - . ./install-jdk.sh -f 12
            - sudo ln -f -T /bin/bash /bin/sh
          install:
            - cd ./tracers/java/
            - . package.sh build
            - cd ../../server/
            - npm install
          script: npm run test
        - name: docker
          install:
            - cd ./tracers/java/
            - docker image build --no-cache --tag willow:java .
            - cd ../python/
            - docker image build --no-cache --tag willow:python .
            - cd ../../server/
            - docker image build --no-cache --tag willow:server .
          script: |
            docker container run --rm --interactive --tty --volume /var/run/docker.sock:/var/run/docker.sock \
              --env TRACER_JAVA="docker run -i willow:java#public class Main{public static void main(String[] a){}}#error+-" \
              --env TRACER_PYTHON="docker run -i willow:python##error+-" \
              willow:server \
              npm run test-base
        #
        #
        ### deploy ###
        - stage: deploy
          name: deploy
          # using install because no deploy provider will help to deploy on google compute engines
          before_install:
            - echo $GCLOUD_SERVICE_ACCOUNT_KEY | base64 -di | gcloud auth activate-service-account --key-file=-
            - gcloud config set project $GCLOUD_PROJECT_NAME
            - gcloud config set compute/zone $GCLOUD_PROJECT_ZONE
            - gcloud config list
            - |
              gcloud compute instances create willow-instance \
                  --service-account=$GCLOUD_SERVICE_ACCOUNT_NAME \
                  --image=cos-stable-72-11316-171-0 --image-project=cos-cloud --machine-type=n1-standard-1 \
                    --subnet=default --tags=http-server --boot-disk-size=10GB || true
            - |
              gcloud compute firewall-rules create default-allow-http \
                  --direction=INGRESS --priority=1000 --network=default --action=ALLOW \
                  --rules=tcp:80 --source-ranges=0.0.0.0/0 --target-tags=http-server || true
          install:
            - DEPLOY_SCRIPT=$(cat ./deploy.sh)
            - gcloud compute ssh willow-instance -- sh -c "$DEPLOY_SCRIPT"

stages:
    - name: test
      if: branch = master
    - name: deploy
      if: branch = deploy
