version: 2.1
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11:slim # ubuntu:18.04 + curl + openjdk 11 (heavy to install in steps)
    steps:
      - run: apt update
      - run: apt install -y git gnupg2 python
      - run: curl -sL https://deb.nodesource.com/setup_11.x | bash -
      - run: apt install -y nodejs
      - run: rm /usr/bin/python
      - run: ln /usr/bin/python3 /usr/bin/python
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: npm install
      - run: npm run test