version: 2.1
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11:slim # ubuntu:18.04 + curl + openjdk 11 (heavy to install in steps)
    steps:
      - run:
          name: configure environment
          command: |
            apt update
            apt install -y git gnupg2 python
            curl -sL https://deb.nodesource.com/setup_11.x | bash -
            apt install -y nodejs
            rm /usr/bin/python
            ln /usr/bin/python3 /usr/bin/python
      - checkout
      - run:
          name: fetch git submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: download dependencies
          command: npm install
      - run:
          name: test
          command: npm run test