name: ci

on:
  push:
    branches:
      - master

jobs:
  test-bare-metal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: '12'
      - uses: actions/setup-python
        with:
          python-version: '3'
          architecture: 'x64'
      - uses: actions/setup-java
        with:
          java-version: '12'
          architecture: x64
      - name: Check versions
        run: |
          node --version
          python --version
          java -version

  test-docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker --version

  publish-docker-images:
    needs: [test-bare-metal, test-docker]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'testing jobs and steps'
