name: ci

on:
  push:
    branches:
      - master

jobs:
#   test-bare-metal:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12'
#       - uses: actions/setup-python@v1
#         with:
#           python-version: '3.7'
#           architecture: x64
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12'
#           architecture: x64
#       - name: build
#         run: |
#           cd ./tracers/java
#           . package.sh build
#           cd ../../server
#           npm install
#       - name: test tracer
#         run: |
#           cd ./tracers/java
#           echo '{}' | . ./package.sh start || true
#           cd ../python
#           echo '{}' | . ./package.sh start || true
#       - name: test
#         run: |
#           cd ./server
#           npm run test

  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          cd ./tracers/java/
          docker image build --no-cache --tag willow:java .
          cd ../python/
          docker image build --no-cache --tag willow:python .
          cd ../../server/
          docker image build --no-cache --tag willow:server .
      - name: test
        run: |
          docker container run --interactive --volume /var/run/docker.sock:/var/run/docker.sock \
            --env TRACER_JAVA="docker run -i willow:java#public class Main{public static void main(String[] a){}}#error+-" \
            --env TRACER_PYTHON="docker run -i willow:python##error+-" \
            willow:server \
            npm run test-base
      - name: publish
        run: |
          docker login docker.pkg.github.com --username pedro00dk --password ${{ secrets.PASSWORD }}
          docker tag willow:java docker.pkg.github.com/pedro00dk/willow/java
          docker push docker.pkg.github.com/pedro00dk/willow/java
