name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          cd ./tracers/java/
          docker image build --pull --no-cache --tag willow-java .
          cd ../python/
          docker image build --pull --no-cache --tag willow-python .
          cd ../../server/
          docker image build --pull --no-cache --tag willow-server .
      - name: test
        run: |
          exit 0
        # tests temporally disable due to jest missing support to ES module imports
        #   docker container run --interactive --volume /var/run/docker.sock:/var/run/docker.sock \
        #     --env TRACER_JAVA="docker run -i willow-java#public class Main{public static void main(String[] a){}}#error+-" \
        #     --env TRACER_PYTHON="docker run -i willow-python##error+-" \
        #     willow-server \
        #     npm run test-base
